Lightning/Lightning/Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lightning.Data;
using Lightning.Models.DBModels;
using Microsoft.AspNetCore.Identity;

namespace Lightning.Controllers
{
    public class RequestsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<LightningUser> _userManager;

        public RequestsController(ApplicationDbContext context, UserManager<LightningUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: Requests
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return this.Redirect("/");
            }
            else
            {
                if (User.Identity.Name == "admin@abv.bg")
                {
                    return View(await _context.Requests.ToListAsync());
                }
                else
                {
                    return View(await _context.Requests.Where(x => x.LightningUser.Id == user.Id).ToListAsync());
                }

            }
        }

        // GET: Requests/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var request = await _context.Requests
                .FirstOrDefaultAsync(m => m.Id == id);
            if (request == null)
            {
                return NotFound();
            }

            return View(request);
        }

        // GET: Requests/Create
        public async Task<IActionResult> Create()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return this.Redirect("/");
            }

            return View();
        }

        // POST: Requests/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Status,Content,DateFrom,DateTo,Package,Address")] Request request)
        {
            var user = await _userManager.GetUserAsync(User);
            if (ModelState.IsValid)
            {
                var requestToAdd = request.LightningUser = user;
                var changeStatus = request.Status = "Изчакване";
                _context.Add(request);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(request);
        }

        // GET: Requests/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var request = await _context.Requests.FindAsync(id);
            if (request == null)
            {
                return NotFound();
            }
            return View(request);
        }

        // POST: Requests/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        public async Task<IActionResult> RejectStatus(int id, [Bind("Id,Status,Content,DateFrom,DateTo,Package,Address")] Request request)
        {
            if (id != request.Id)
            {
                return NotFound();
            }

            Request requestFromDB = _context.Requests.Where(x => x.Id == request.Id).Select(x => new Request
            {
                Id = x.Id,
                Status = "Отхвърлена",
                LightningUser = x.LightningUser,
                Content = x.Content,
                DateFrom = x.DateFrom,
                DateTo = x.DateTo,
                Package = x.Package,
                Address = x.Address
            }).FirstOrDefault();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(requestFromDB);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RequestExists(request.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(request);
        }

        public async Task<IActionResult> ApproveStatus(int id, [Bind("Id,Status,Content,DateFrom,DateTo,Package,Address")] Request request)
        {
            if (id != request.Id)
            {
                return NotFound();
            }

            Request requestFromDB = _context.Requests.Where(x => x.Id == request.Id).Select(x => new Request
            { Id = x.Id,
              Status = "Одобрена",
              LightningUser = x.LightningUser,
              Content = x.Content,
              DateFrom = x.DateFrom,
              DateTo = x.DateTo,
              Package = x.Package,
              Address = x.Address}).FirstOrDefault();

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(requestFromDB);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RequestExists(request.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(request);
        }

        // GET: Requests/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var request = await _context.Requests
                .FirstOrDefaultAsync(m => m.Id == id);
            if (request == null)
            {
                return NotFound();
            }

            return View(request);
        }

        // POST: Requests/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var request = await _context.Requests.FindAsync(id);
            _context.Requests.Remove(request);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RequestExists(int id)
        {
            return _context.Requests.Any(e => e.Id == id);
        }
    }
}

Lightning/Lightning/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lightning</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light" style="height: 90px;">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lightning</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Offers">Оферти</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Requests" asp-action="Create">Заяви пакет</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main role="main">
        @RenderBody()
    </main>

    <footer class="border-top custom-footer" style="background-color: #676767;">
        <div class="footer-col">
            <div style="display:flex;">
                <div style="margin-right: 2rem;">
                    <p class="footer-paragraphs">Адрес: Ул. Атанас Томов 6</p>

                    <p class="footer-paragraphs">Телефон: 0700 16 225</p>

                    <a class="footer-links" href="mailto:lightning@abv.bg">support@lightning.bg</a>
                </div>
                <div>
                    <p class="footer-paragraphs">Работно време:</p>
                    <p class="footer-paragraphs">Пон-Петък: 9:30 до 18:30</p>
                    <p class="footer-paragraphs">Събота: 8:30 до 13:00</p>
                    <p class="footer-paragraphs">Неделя: Почивен ден</p>
                </div>
            </div>
        </div>
        <div class="footer-col">
            <div style="display:grid;">
                <a class="footer-links" asp-area="" asp-controller="Home" asp-action="Privacy">Условия за ползване</a>
                <a class="footer-links" asp-area="" asp-controller="Home" asp-action="AboutUs">За нас</a>
            </div>

            <p class="footer-paragraphs">&copy; 2020 - Lightning</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>